//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.default_Grab;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean ShowMap
        {
            get
            {
                return SteamVR_Actions.default_ShowMap;
            }
        }
        
        public virtual SteamVR_Action_Boolean UpDpad
        {
            get
            {
                return SteamVR_Actions.default_UpDpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean DownDpad
        {
            get
            {
                return SteamVR_Actions.default_DownDpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftDpad
        {
            get
            {
                return SteamVR_Actions.default_LeftDpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightDpad
        {
            get
            {
                return SteamVR_Actions.default_RightDpad;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrackPadPosition
        {
            get
            {
                return SteamVR_Actions.default_TrackPadPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean PressTrackPad
        {
            get
            {
                return SteamVR_Actions.default_PressTrackPad;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchTrackPad
        {
            get
            {
                return SteamVR_Actions.default_TouchTrackPad;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
